# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  box2d_config = debug_x64
  Hitbox_config = debug_x64
  ImGui_config = debug_x64
  Framework_config = debug_x64

else ifeq ($(config),release_x64)
  box2d_config = release_x64
  Hitbox_config = release_x64
  ImGui_config = release_x64
  Framework_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := box2d Hitbox ImGui Framework

.PHONY: all clean help $(PROJECTS) vendor

all: $(PROJECTS)

vendor: Hitbox ImGui box2d

box2d:
ifneq (,$(box2d_config))
	@echo "==== Building box2d ($(box2d_config)) ===="
	@${MAKE} --no-print-directory -C vendor/box2d/lib/build -f Makefile config=$(box2d_config)
endif

Hitbox:
ifneq (,$(Hitbox_config))
	@echo "==== Building Hitbox ($(Hitbox_config)) ===="
	@${MAKE} --no-print-directory -C vendor/hitbox/lib/build -f Makefile config=$(Hitbox_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C vendor/imgui/lib/build -f Makefile config=$(ImGui_config)
endif

Framework: box2d ImGui Hitbox
ifneq (,$(Framework_config))
	@echo "==== Building Framework ($(Framework_config)) ===="
	@${MAKE} --no-print-directory -C _build -f Makefile config=$(Framework_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/box2d/lib/build -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/hitbox/lib/build -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/imgui/lib/build -f Makefile clean
	@${MAKE} --no-print-directory -C _build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   box2d"
	@echo "   Hitbox"
	@echo "   ImGui"
	@echo "   Framework"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"